### ISSUE TITLE
Uglify 메모리 문제

### ISSUE THREAD

**Issue by Curzy** [Curzy/Wolsemap#14]
ec2 t2.micro 인스턴스에서 webpack 번들링시 Uglify plugin이 메모리 사용량이 많아 번들링이 중단됨. 일단 빼놨는데 다른 플러그인을 찾던가 인스턴스를 키우던가

**Comment by incleaf** [comment]
오늘 v4가 릴리즈 됐는데 https://github.com/webpack/webpack/releases/tag/v4.0.0 이걸로 업데이트 해보죠

**Comment by Curzy** [comment]
@incleaf 프로젝트 생성이 webpack v1.5때 했는데 버전업 확 하면서 바꿔줄건 많은가요

**Comment by incleaf** [comment]
저도 웹팩 지식이 v1에 머물러 있는데염

**Comment by yangroro** [comment]
그 정도면 업데이트 해줘야하지 않을까요;;

**Comment by sinwoobang** [comment]
빨리 해주세요;;

**Comment by yangroro** [comment]
#13 EC2가 없으면 함께 해결됩니다.

**Comment by Curzy** [comment]
웹팩 버전업으로 해결됬습니다 https://github.com/Curzy/Wolsemap/commit/352f24fc2334d51478e793f3cb696a5fe799151c
